### ISSUE TITLE
Any plan for making it available through conda-forge?

### ISSUE THREAD

**Issue by santisoler** [nhoad/flake8-unused-arguments#12]
Hi there! Thanks for this awesome plugin! I'm wondering if there's any plan for making it available through [conda-forge](https://conda-forge.org/).

Most users of open-source scientific projects (like [Fatiando a Terra](https://www.fatiando.org), the one I'm mostly involved with) make use of the Anaconda Python distribution, or any of their alternatives that ship the `conda` package manager (e.g. Miniconda, Miniforge, etc). It would be awesome to have `flake8-unused-arguments` available for installation through the `conda` package manager, and the easiest solution for pure Python packages is `conda-forge`.

A lot of widely used flake8 extensions are already available in `conda-forge`: `flake8-bugbear`, `flake8-simplify`, `flake8-variables-names`, `flake8-functions`, `flake8-builtins`, `flake8-comprehensions`, `pep8-naming`, `flake8-mutable`.
Would be great to see `flake8-unused-arguments` in that list.

**Comment by nhoad** [comment]
Hi! I've never used Anaconda, or conda-forge. Could you point me to documentation for how I'd make it available on there? Then I can let you know how feasible it is :)

**Comment by santisoler** [comment]
Hi @nhoad! Thanks for the swift reply!

Here you can find the instructions on how to "Add a recipe" to conda-forge: https://conda-forge.org/#add_recipe

I think that creating the recipe is the most demanding job. Then, whenever you make a Release through GitHub, conda-forge will automatically open a PR in the feedstock repository. Once you merge it, the latest release will be available through conda-forge.
There's no need for you to get familiar with Anaconda or conda. I can help if you need it!

**Comment by santisoler** [comment]
Hi @nhoad! I would like to let you know that since a couple of minutes ago we have `flake8-unused-arguments` available in conda-forge. So now anyone can install it with `conda` or `mamba` by running:

```
conda install -c conda-forge flake8-unused-arguments
```

I signed myself as maintainer of the [flake8-unused-arguments feedstock repo](https://github.com/conda-forge/flake8-unused-arguments-feedstock), but I'm happy to share the load with whoever might be interesting. Usually there's not to much to do, just to update the feedstock after every upstream release. I'm fine with being the only maintainer though, no pressure!

I think you can close this issue now. Thanks again for developing this plugin, it's really helpful!

**Comment by nhoad** [comment]
Santiago you’re the best!! Thank you!! Happy to let you be the maintainer, if there’s a preferred way for me to notify you about new releases then just let me know :)

Thank you again!! I’ll close this now.

**Comment by santisoler** [comment]
You're very welcomed! And setting up the conda-forge repo was much less work than actually writing and maintaining this plugin, so kudos to you!

I'm subscribed to this repo, so I'll get notified of future releases. But if for some reason I forget to update the feedstock after a release, feel free to ping me in an issue. You can also email me to the address that it's my profile.
