### ISSUE TITLE
Feature request: ignore underscore arguments

### ISSUE THREAD

**Issue by Fogapod** [nhoad/flake8-unused-arguments#13]
```python
def a(_test):
    pass
```
This produces warning:
`a.py:1:7: U101 Unused argument '_test'`

This is pretty much a common practice to not raise warnings if argument name starts with underscore

**Comment by nhoad** [comment]
Per the documentation, `U101` is produced when an argument starts with an underscore. If you don't want errors for those, ignore `U101`.
