### ISSUE TITLE
The plugin is working, but the column is always 1:

### ISSUE THREAD

**Issue by thales-maciel** [nhoad/flake8-unused-arguments#2]
Linting this:

![image](https://user-images.githubusercontent.com/48626109/86313982-d94bd600-bbfc-11ea-97f8-3db6865da76d.png)

Gives me:

`tests.py:11:1: U100 Unused argument 'a'`

`tests.py:11:1: U100 Unused argument 'b'`

**Comment by nhoad** [comment]
Good catch! Thanks for reporting :) I'll try to fix this up over the weekend.

**Comment by nhoad** [comment]
Fixed! I've released 0.0.5 which does a much better job.
