### ISSUE TITLE
Plugin breaks `flake8 --help`

### ISSUE THREAD

**Issue by ethframe** [nhoad/flake8-unused-arguments#21]
Plugin breaks `flake8 --help` because some option descriptions are tuples, not strings: https://github.com/nhoad/flake8-unused-arguments/blob/e56de713a5b0a360a98caa3aecb3dd8548fbf743/flake8_unused_arguments.py#L81-L83 (notice the trailing comma)

```python
Traceback (most recent call last):
  ...
  File "...\argparse.py", line 620, in _expand_help
    return self._get_help_string(action) % params
TypeError: unsupported operand type(s) for %: 'tuple' and 'dict'
```

**Comment by nhoad** [comment]
Neat, thank you for reporting! I'll try to have a fix out sometime this week.
