### ISSUE TITLE
Don't raise U100 for stub functions (functions with just `...` as body)

### ISSUE THREAD

**Issue by GideonBear** [nhoad/flake8-unused-arguments#23]

**Comment by jonyscathe** [comment]
Also started getting this. Seems to be a python3.11 issue

**Comment by GideonBear** [comment]
> Also started getting this. Seems to be a python3.11 issue

I get it on python 3.9, I don't think it's a version specific issue

**Comment by GideonBear** [comment]
Wait, I might just be really dumb.

**Comment by GideonBear** [comment]
I completely forgot there are already configuration options for this. I enabled `unused-arguments-ignore-stubs` and it works.
